/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/VersantHealth.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={materials.Other_EmissionCeleste} geometry={nodes.EmissionCeleste.geometry} />
      <mesh material={materials.Det_Arcade} geometry={nodes.Det_ArcadeAtlas.geometry} />
      <mesh material={materials.Other_EmissionRojo} geometry={nodes.EmissionRojo.geometry} />
      <mesh material={materials.Atlas_03} geometry={nodes.Atlas03.geometry} />
      <mesh material={materials.Other_Vidrio} geometry={nodes.Vidrio.geometry} />
      <mesh material={materials.Other_EmissionAmarillo} geometry={nodes.EmissionAmarillo.geometry} />
      <mesh material={materials.Atlas_01} geometry={nodes.Atlas01.geometry} />
      <mesh material={materials.Atlas_04} geometry={nodes.Atlas04.geometry} />
      <mesh material={materials.Atlas_02} geometry={nodes.Atlas02.geometry} />
      <mesh material={materials.Atlas_Color} geometry={nodes.AtlasColor.geometry} />
      <mesh material={materials.Lg_ArcadeyColor} geometry={nodes.Lg_ArcadeAtlas.geometry} />
      <mesh material={materials.Fondo} geometry={nodes.Fondo.geometry} />
      <mesh material={materials.Other_Outline} geometry={nodes.Plano_VisionLoss.geometry} />
      <mesh material={materials.Other_Outline} geometry={nodes.Plano_Theater.geometry} />
      <mesh material={materials.Other_Outline} geometry={nodes.Plano_Child.geometry} />
      <mesh material={materials.Other_Outline} geometry={nodes.Plano_Do.geometry} />
      <mesh material={materials.Other_Outline} geometry={nodes.Plano_Arcade.geometry} />
      <mesh material={materials.Other_Outline} geometry={nodes.Plano_Sweepstakes.geometry} />
      <mesh material={materials.Other_Outline} geometry={nodes.Plano_Yoga.geometry} />
      <mesh material={materials.Other_Outline} geometry={nodes.Plano_EyeWellness.geometry} />
      <mesh material={materials.Other_Outline} geometry={nodes.Plano_Workplace.geometry} />
      <mesh material={materials.Other_Outline} geometry={nodes.Plano_Benefit.geometry} />
      <mesh material={materials.Other_Outline} geometry={nodes.Plano_NeedAssistance.geometry} />
      <mesh material={materials.Other_Outline} geometry={nodes.Plano_YourHealth.geometry} />
      <mesh material={materials.Other_Outline} geometry={nodes.Plano_VisionToLearn.geometry} />
      <mesh material={materials.Other_Outline} geometry={nodes.Plano_Thinking.geometry} />
      <mesh material={materials.Other_Outline} geometry={nodes.Plano_EnrollToday.geometry} />
      <mesh material={materials.Other_Outline} geometry={nodes.Plano_EnrolliBenefit.geometry} />
      <mesh material={materials.Other_Outline} geometry={nodes.Plano_MobileMedical.geometry} />
      <mesh material={materials.Other_Outline} geometry={nodes.Plano_SunlifeAccident.geometry} />
      <mesh material={materials.Other_Outline} geometry={nodes.Plano_SunlifeCritical.geometry} />
      <mesh material={materials.Other_Outline} geometry={nodes.Plano_SunlifeHospital.geometry} />
      <mesh material={materials.Other_Outline} geometry={nodes.Plano_Transamerica.geometry} />
      <mesh material={materials.Other_Outline} geometry={nodes.Plano_MetlifePet.geometry} />
      <mesh material={materials.Other_Outline} geometry={nodes.Plano_LegalShield.geometry} />
      <mesh material={materials.Other_Outline} geometry={nodes.Plano_IDshield.geometry} />
      <mesh material={materials.Other_Outline} geometry={nodes.Borde_Theater.geometry} />
      <mesh material={materials.Other_Outline} geometry={nodes.Plano_MobileTeladoc.geometry} />
      <mesh material={materials.Other_Outline} geometry={nodes.Plano_MobileDental.geometry} />
      <mesh material={materials.Other_Outline} geometry={nodes.Plano_MobileHSA.geometry} />
      <mesh material={materials.Other_Outline} geometry={nodes.Plano_MobileVision.geometry} />
      <mesh material={materials.Other_Outline} geometry={nodes.Plano_Mobile401K.geometry} />
    </group>
  )
}

useGLTF.preload('/VersantHealth.gltf')
